MedPull/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace= 'app')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/urls.py
from django.contrib import admin
from django.urls import path
from .views import home, loginUser, logoutUser, registerUser, fillOutInfo, upload_translate_view, upload_file
from . import views

app_name = 'app'
urlpatterns = [
    path('', home, name='home'),
    path('login/', loginUser, name='login'),
    path('logout/', logoutUser, name='logout'),
    path('register/', registerUser, name='register'),
    path('information/', fillOutInfo, name='information'),
    path('translate/', upload_translate_view, name='translate'),
    path('extract/', upload_file, name='extract'),
    path('rag-query/', views.rag_query, name='rag-query')
] 

templates/main.html
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/main.css' %}">
    <title>MedPull</title>
</head>
<body>
    {% include 'navbar.html' %}
    <div class="wrapper">
        {% block content %}
        {% endblock content %}
    </div>
</body>
</html>

templates/navbar.html
{% if request.user.is_authenticated %}
  <nav class="topnav">
    <a href="{% url 'app:home' %}">home</a>
    <a href="{% url 'app:information' %}">fill out your information</a>
    <a href="{% url 'app:translate' %}">translate a form</a>
    <a href="{% url 'app:extract' %}">extract a form</a>   <!-- ✅ New tab -->
    <a href="{% url 'app:logout' %}">logout</a>
  </nav>
{% else %}
  <nav class="topnav">
    <a href="{% url 'app:home' %}">home</a>
    <a href="{% url 'app:login' %}">login/register</a>
  </nav>
{% endif %}